/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pe.gui;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.plaf.basic.BasicScrollPaneUI;
import javax.swing.plaf.basic.BasicTableUI;



/**
 *
 * @author User
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        jTable2.getTableHeader().setBackground(new Color (0,153,204));
        jTable2.getTableHeader().setOpaque(false);
        jButton8.setUI(new BasicButtonUI());
        
        jScrollPane2.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                 this.thumbColor = new Color (0,153,204);
            }
        });;
        jScrollPane2.setOpaque(false);
        jScrollPane2.getVerticalScrollBar().setBackground(new Color (28,34,59));
        
        
        JButton [] btns = {jButton2, jButton3, jButton1, jButton4, jButton5, jButton6, jButton7};
        for (JButton btn : btns){
            btn.setBackground(new Color (48,61,151));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color (50,30,150));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color (48,61,151));
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rooPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        centerUpPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jPanel58 = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jPanel65 = new javax.swing.JPanel();
        jPanel66 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel67 = new javax.swing.JPanel();
        jPanel68 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jPanel69 = new javax.swing.JPanel();
        jPanel70 = new javax.swing.JPanel();
        jPanel71 = new javax.swing.JPanel();
        jPanel72 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel73 = new javax.swing.JPanel();
        jPanel74 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        jPanel75 = new javax.swing.JPanel();
        jPanel76 = new javax.swing.JPanel();
        jPanel77 = new javax.swing.JPanel();
        jPanel78 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel79 = new javax.swing.JPanel();
        jPanel80 = new javax.swing.JPanel();
        jTextField12 = new javax.swing.JTextField();
        jPanel81 = new javax.swing.JPanel();
        jPanel82 = new javax.swing.JPanel();
        jPanel83 = new javax.swing.JPanel();
        jPanel84 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel85 = new javax.swing.JPanel();
        jPanel86 = new javax.swing.JPanel();
        jTextField13 = new javax.swing.JTextField();
        jPanel87 = new javax.swing.JPanel();
        jPanel88 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel89 = new javax.swing.JPanel();
        jPanel90 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel91 = new javax.swing.JPanel();
        jPanel92 = new javax.swing.JPanel();
        jTextField14 = new javax.swing.JTextField();
        jPanel93 = new javax.swing.JPanel();
        jPanel94 = new javax.swing.JPanel();
        jPanel95 = new javax.swing.JPanel();
        jPanel96 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel97 = new javax.swing.JPanel();
        jPanel98 = new javax.swing.JPanel();
        jTextField15 = new javax.swing.JTextField();
        jPanel99 = new javax.swing.JPanel();
        jPanel100 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel51 = new javax.swing.JPanel();
        centerDownPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rooPanel.setBackground(new java.awt.Color(28, 34, 59));
        rooPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 34, 59), 4, true));
        rooPanel.setLayout(new java.awt.BorderLayout(10, 0));

        sidePanel.setBackground(new java.awt.Color(48, 61, 151));
        sidePanel.setMinimumSize(new java.awt.Dimension(149, 900));
        sidePanel.setPreferredSize(new java.awt.Dimension(170, 980));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Orbitron", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER NAME");
        jLabel1.setToolTipText("");
        sidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        jLabel2.setFont(new java.awt.Font("Orbitron", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIENVENIDO");
        jLabel2.setToolTipText("");
        sidePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pe/icons/Imagen2.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        sidePanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 100));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pe/icons/lupa1.png"))); // NOI18N
        sidePanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 90, 100));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pe/icons/add1.png"))); // NOI18N
        sidePanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 90, 100));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pe/icons/trashcan1.png"))); // NOI18N
        sidePanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 90, 100));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pe/icons/impresora1.png"))); // NOI18N
        sidePanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 90, 100));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pe/icons/calendar21.png"))); // NOI18N
        sidePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 790, 90, 100));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pe/icons/calendar21.png"))); // NOI18N
        sidePanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 90, 100));

        rooPanel.add(sidePanel, java.awt.BorderLayout.WEST);

        centerPanel.setBackground(new java.awt.Color(28, 34, 59));
        centerPanel.setPreferredSize(new java.awt.Dimension(1500, 800));
        centerPanel.setLayout(new java.awt.BorderLayout(0, 10));

        centerUpPanel.setBackground(new java.awt.Color(28, 34, 59));
        centerUpPanel.setPreferredSize(new java.awt.Dimension(491, 600));
        centerUpPanel.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanel2.setBackground(new java.awt.Color(58, 120, 220));
        jPanel2.setLayout(new java.awt.GridLayout(8, 0, 0, 40));

        jPanel3.setBackground(new java.awt.Color(58, 120, 220));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(58, 120, 220));
        jLabel3.setFont(new java.awt.Font("Orbitron", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DATOS PERSONALES");
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel54.setLayout(new java.awt.BorderLayout());

        jPanel55.setBackground(new java.awt.Color(58, 120, 220));
        jPanel55.setPreferredSize(new java.awt.Dimension(200, 58));
        jPanel55.setLayout(new java.awt.BorderLayout());

        jLabel19.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("   Nombre  ");
        jLabel19.setToolTipText("");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel19.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel55.add(jLabel19, java.awt.BorderLayout.CENTER);

        jPanel54.add(jPanel55, java.awt.BorderLayout.WEST);

        jPanel56.setBackground(new java.awt.Color(58, 120, 220));
        jPanel56.setLayout(new java.awt.BorderLayout());

        jPanel57.setBackground(new java.awt.Color(58, 120, 220));
        jPanel57.setPreferredSize(new java.awt.Dimension(20, 58));
        jPanel57.setLayout(new java.awt.BorderLayout());

        jTextField8.setBackground(new java.awt.Color(58, 120, 220));
        jTextField8.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jTextField8.setPreferredSize(new java.awt.Dimension(2, 30));
        jPanel57.add(jTextField8, java.awt.BorderLayout.SOUTH);

        jPanel58.setBackground(new java.awt.Color(58, 120, 220));
        jPanel58.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel58Layout = new javax.swing.GroupLayout(jPanel58);
        jPanel58.setLayout(jPanel58Layout);
        jPanel58Layout.setHorizontalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        jPanel58Layout.setVerticalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel57.add(jPanel58, java.awt.BorderLayout.NORTH);

        jPanel56.add(jPanel57, java.awt.BorderLayout.CENTER);

        jPanel59.setBackground(new java.awt.Color(58, 120, 220));
        jPanel59.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel59Layout = new javax.swing.GroupLayout(jPanel59);
        jPanel59.setLayout(jPanel59Layout);
        jPanel59Layout.setHorizontalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel59Layout.setVerticalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel56.add(jPanel59, java.awt.BorderLayout.EAST);

        jPanel54.add(jPanel56, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel54);

        jPanel65.setLayout(new java.awt.BorderLayout());

        jPanel66.setBackground(new java.awt.Color(58, 120, 220));
        jPanel66.setPreferredSize(new java.awt.Dimension(200, 58));
        jPanel66.setLayout(new java.awt.BorderLayout());

        jLabel21.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("   Nombre  ");
        jLabel21.setToolTipText("");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel21.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel66.add(jLabel21, java.awt.BorderLayout.CENTER);

        jPanel65.add(jPanel66, java.awt.BorderLayout.WEST);

        jPanel67.setBackground(new java.awt.Color(58, 120, 220));
        jPanel67.setLayout(new java.awt.BorderLayout());

        jPanel68.setBackground(new java.awt.Color(58, 120, 220));
        jPanel68.setPreferredSize(new java.awt.Dimension(20, 58));
        jPanel68.setLayout(new java.awt.BorderLayout());

        jTextField10.setBackground(new java.awt.Color(58, 120, 220));
        jTextField10.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jTextField10.setPreferredSize(new java.awt.Dimension(2, 30));
        jPanel68.add(jTextField10, java.awt.BorderLayout.SOUTH);

        jPanel69.setBackground(new java.awt.Color(58, 120, 220));
        jPanel69.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel69Layout = new javax.swing.GroupLayout(jPanel69);
        jPanel69.setLayout(jPanel69Layout);
        jPanel69Layout.setHorizontalGroup(
            jPanel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        jPanel69Layout.setVerticalGroup(
            jPanel69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel68.add(jPanel69, java.awt.BorderLayout.NORTH);

        jPanel67.add(jPanel68, java.awt.BorderLayout.CENTER);

        jPanel70.setBackground(new java.awt.Color(58, 120, 220));
        jPanel70.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel70Layout = new javax.swing.GroupLayout(jPanel70);
        jPanel70.setLayout(jPanel70Layout);
        jPanel70Layout.setHorizontalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel70Layout.setVerticalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel67.add(jPanel70, java.awt.BorderLayout.EAST);

        jPanel65.add(jPanel67, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel65);

        jPanel71.setLayout(new java.awt.BorderLayout());

        jPanel72.setBackground(new java.awt.Color(58, 120, 220));
        jPanel72.setPreferredSize(new java.awt.Dimension(200, 58));
        jPanel72.setLayout(new java.awt.BorderLayout());

        jLabel22.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("   Nombre  ");
        jLabel22.setToolTipText("");
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel22.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel72.add(jLabel22, java.awt.BorderLayout.CENTER);

        jPanel71.add(jPanel72, java.awt.BorderLayout.WEST);

        jPanel73.setBackground(new java.awt.Color(58, 120, 220));
        jPanel73.setLayout(new java.awt.BorderLayout());

        jPanel74.setBackground(new java.awt.Color(58, 120, 220));
        jPanel74.setPreferredSize(new java.awt.Dimension(20, 58));
        jPanel74.setLayout(new java.awt.BorderLayout());

        jTextField11.setBackground(new java.awt.Color(58, 120, 220));
        jTextField11.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jTextField11.setPreferredSize(new java.awt.Dimension(2, 30));
        jPanel74.add(jTextField11, java.awt.BorderLayout.SOUTH);

        jPanel75.setBackground(new java.awt.Color(58, 120, 220));
        jPanel75.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel75Layout = new javax.swing.GroupLayout(jPanel75);
        jPanel75.setLayout(jPanel75Layout);
        jPanel75Layout.setHorizontalGroup(
            jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        jPanel75Layout.setVerticalGroup(
            jPanel75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel74.add(jPanel75, java.awt.BorderLayout.NORTH);

        jPanel73.add(jPanel74, java.awt.BorderLayout.CENTER);

        jPanel76.setBackground(new java.awt.Color(58, 120, 220));
        jPanel76.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel76Layout = new javax.swing.GroupLayout(jPanel76);
        jPanel76.setLayout(jPanel76Layout);
        jPanel76Layout.setHorizontalGroup(
            jPanel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel76Layout.setVerticalGroup(
            jPanel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel73.add(jPanel76, java.awt.BorderLayout.EAST);

        jPanel71.add(jPanel73, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel71);

        jPanel77.setLayout(new java.awt.BorderLayout());

        jPanel78.setBackground(new java.awt.Color(58, 120, 220));
        jPanel78.setPreferredSize(new java.awt.Dimension(200, 58));
        jPanel78.setLayout(new java.awt.BorderLayout());

        jLabel23.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("   Nombre  ");
        jLabel23.setToolTipText("");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel23.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel78.add(jLabel23, java.awt.BorderLayout.CENTER);

        jPanel77.add(jPanel78, java.awt.BorderLayout.WEST);

        jPanel79.setBackground(new java.awt.Color(58, 120, 220));
        jPanel79.setLayout(new java.awt.BorderLayout());

        jPanel80.setBackground(new java.awt.Color(58, 120, 220));
        jPanel80.setPreferredSize(new java.awt.Dimension(20, 58));
        jPanel80.setLayout(new java.awt.BorderLayout());

        jTextField12.setBackground(new java.awt.Color(58, 120, 220));
        jTextField12.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jTextField12.setPreferredSize(new java.awt.Dimension(2, 30));
        jPanel80.add(jTextField12, java.awt.BorderLayout.SOUTH);

        jPanel81.setBackground(new java.awt.Color(58, 120, 220));
        jPanel81.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel81Layout = new javax.swing.GroupLayout(jPanel81);
        jPanel81.setLayout(jPanel81Layout);
        jPanel81Layout.setHorizontalGroup(
            jPanel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        jPanel81Layout.setVerticalGroup(
            jPanel81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel80.add(jPanel81, java.awt.BorderLayout.NORTH);

        jPanel79.add(jPanel80, java.awt.BorderLayout.CENTER);

        jPanel82.setBackground(new java.awt.Color(58, 120, 220));
        jPanel82.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel82Layout = new javax.swing.GroupLayout(jPanel82);
        jPanel82.setLayout(jPanel82Layout);
        jPanel82Layout.setHorizontalGroup(
            jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel82Layout.setVerticalGroup(
            jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel79.add(jPanel82, java.awt.BorderLayout.EAST);

        jPanel77.add(jPanel79, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel77);

        jPanel83.setLayout(new java.awt.BorderLayout());

        jPanel84.setBackground(new java.awt.Color(58, 120, 220));
        jPanel84.setPreferredSize(new java.awt.Dimension(200, 58));
        jPanel84.setLayout(new java.awt.BorderLayout());

        jLabel24.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("   Nombre  ");
        jLabel24.setToolTipText("");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel24.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel84.add(jLabel24, java.awt.BorderLayout.CENTER);

        jPanel83.add(jPanel84, java.awt.BorderLayout.WEST);

        jPanel85.setBackground(new java.awt.Color(58, 120, 220));
        jPanel85.setLayout(new java.awt.BorderLayout());

        jPanel86.setBackground(new java.awt.Color(58, 120, 220));
        jPanel86.setPreferredSize(new java.awt.Dimension(20, 58));
        jPanel86.setLayout(new java.awt.BorderLayout());

        jTextField13.setBackground(new java.awt.Color(58, 120, 220));
        jTextField13.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jTextField13.setPreferredSize(new java.awt.Dimension(2, 30));
        jPanel86.add(jTextField13, java.awt.BorderLayout.SOUTH);

        jPanel87.setBackground(new java.awt.Color(58, 120, 220));
        jPanel87.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel87Layout = new javax.swing.GroupLayout(jPanel87);
        jPanel87.setLayout(jPanel87Layout);
        jPanel87Layout.setHorizontalGroup(
            jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        jPanel87Layout.setVerticalGroup(
            jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel86.add(jPanel87, java.awt.BorderLayout.NORTH);

        jPanel85.add(jPanel86, java.awt.BorderLayout.CENTER);

        jPanel88.setBackground(new java.awt.Color(58, 120, 220));
        jPanel88.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel88Layout = new javax.swing.GroupLayout(jPanel88);
        jPanel88.setLayout(jPanel88Layout);
        jPanel88Layout.setHorizontalGroup(
            jPanel88Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel88Layout.setVerticalGroup(
            jPanel88Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel85.add(jPanel88, java.awt.BorderLayout.EAST);

        jPanel83.add(jPanel85, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel83);

        jPanel24.setBackground(new java.awt.Color(58, 120, 220));
        jPanel24.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel25.setBackground(new java.awt.Color(58, 120, 220));
        jPanel25.setPreferredSize(new java.awt.Dimension(200, 58));
        jPanel25.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("   Estado Civil");
        jLabel9.setToolTipText("");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel9.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel25.add(jLabel9, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel25, java.awt.BorderLayout.WEST);

        jPanel26.setBackground(new java.awt.Color(58, 120, 220));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jPanel27.setBackground(new java.awt.Color(58, 120, 220));
        jPanel27.setPreferredSize(new java.awt.Dimension(15, 20));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel26.add(jPanel27, java.awt.BorderLayout.NORTH);

        jPanel28.setBackground(new java.awt.Color(58, 120, 220));
        jPanel28.setPreferredSize(new java.awt.Dimension(20, 25));
        jPanel28.setLayout(new java.awt.BorderLayout(20, 0));

        jRadioButton2.setBackground(new java.awt.Color(58, 120, 220));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Soltero");
        jPanel28.add(jRadioButton2, java.awt.BorderLayout.LINE_START);

        jRadioButton3.setBackground(new java.awt.Color(58, 120, 220));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Casado");
        jPanel28.add(jRadioButton3, java.awt.BorderLayout.CENTER);

        jPanel26.add(jPanel28, java.awt.BorderLayout.SOUTH);

        jPanel24.add(jPanel26, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel24);

        centerUpPanel.add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(58, 120, 220));
        jPanel1.setLayout(new java.awt.GridLayout(8, 0, 0, 40));

        jLabel10.setBackground(new java.awt.Color(58, 120, 220));
        jLabel10.setFont(new java.awt.Font("Orbitron", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("HORAS");
        jLabel10.setToolTipText("");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel10);

        jPanel89.setLayout(new java.awt.BorderLayout());

        jPanel90.setBackground(new java.awt.Color(58, 120, 220));
        jPanel90.setPreferredSize(new java.awt.Dimension(150, 58));
        jPanel90.setLayout(new java.awt.BorderLayout());

        jLabel25.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("   Nombre  ");
        jLabel25.setToolTipText("");
        jLabel25.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel90.add(jLabel25, java.awt.BorderLayout.CENTER);

        jPanel89.add(jPanel90, java.awt.BorderLayout.WEST);

        jPanel91.setBackground(new java.awt.Color(58, 120, 220));
        jPanel91.setLayout(new java.awt.BorderLayout());

        jPanel92.setBackground(new java.awt.Color(58, 120, 220));
        jPanel92.setPreferredSize(new java.awt.Dimension(20, 58));
        jPanel92.setLayout(new java.awt.BorderLayout());

        jTextField14.setBackground(new java.awt.Color(58, 120, 220));
        jTextField14.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jTextField14.setPreferredSize(new java.awt.Dimension(2, 30));
        jPanel92.add(jTextField14, java.awt.BorderLayout.SOUTH);

        jPanel93.setBackground(new java.awt.Color(58, 120, 220));
        jPanel93.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel93Layout = new javax.swing.GroupLayout(jPanel93);
        jPanel93.setLayout(jPanel93Layout);
        jPanel93Layout.setHorizontalGroup(
            jPanel93Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );
        jPanel93Layout.setVerticalGroup(
            jPanel93Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel92.add(jPanel93, java.awt.BorderLayout.NORTH);

        jPanel91.add(jPanel92, java.awt.BorderLayout.CENTER);

        jPanel94.setBackground(new java.awt.Color(58, 120, 220));
        jPanel94.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel94Layout = new javax.swing.GroupLayout(jPanel94);
        jPanel94.setLayout(jPanel94Layout);
        jPanel94Layout.setHorizontalGroup(
            jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel94Layout.setVerticalGroup(
            jPanel94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel91.add(jPanel94, java.awt.BorderLayout.EAST);

        jPanel89.add(jPanel91, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel89);

        jPanel95.setLayout(new java.awt.BorderLayout());

        jPanel96.setBackground(new java.awt.Color(58, 120, 220));
        jPanel96.setPreferredSize(new java.awt.Dimension(150, 58));
        jPanel96.setLayout(new java.awt.BorderLayout());

        jLabel26.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("   Nombre  ");
        jLabel26.setToolTipText("");
        jLabel26.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel96.add(jLabel26, java.awt.BorderLayout.CENTER);

        jPanel95.add(jPanel96, java.awt.BorderLayout.WEST);

        jPanel97.setBackground(new java.awt.Color(58, 120, 220));
        jPanel97.setLayout(new java.awt.BorderLayout());

        jPanel98.setBackground(new java.awt.Color(58, 120, 220));
        jPanel98.setPreferredSize(new java.awt.Dimension(20, 58));
        jPanel98.setLayout(new java.awt.BorderLayout());

        jTextField15.setBackground(new java.awt.Color(58, 120, 220));
        jTextField15.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jTextField15.setPreferredSize(new java.awt.Dimension(2, 30));
        jPanel98.add(jTextField15, java.awt.BorderLayout.SOUTH);

        jPanel99.setBackground(new java.awt.Color(58, 120, 220));
        jPanel99.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel99Layout = new javax.swing.GroupLayout(jPanel99);
        jPanel99.setLayout(jPanel99Layout);
        jPanel99Layout.setHorizontalGroup(
            jPanel99Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );
        jPanel99Layout.setVerticalGroup(
            jPanel99Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel98.add(jPanel99, java.awt.BorderLayout.NORTH);

        jPanel97.add(jPanel98, java.awt.BorderLayout.CENTER);

        jPanel100.setBackground(new java.awt.Color(58, 120, 220));
        jPanel100.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel100Layout = new javax.swing.GroupLayout(jPanel100);
        jPanel100.setLayout(jPanel100Layout);
        jPanel100Layout.setHorizontalGroup(
            jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel100Layout.setVerticalGroup(
            jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel97.add(jPanel100, java.awt.BorderLayout.EAST);

        jPanel95.add(jPanel97, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel95);

        jPanel37.setLayout(new java.awt.BorderLayout());

        jPanel38.setBackground(new java.awt.Color(58, 120, 220));
        jPanel38.setPreferredSize(new java.awt.Dimension(200, 58));
        jPanel38.setLayout(new java.awt.BorderLayout());

        jLabel13.setFont(new java.awt.Font("Orbitron", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("   Sueldo bruto");
        jLabel13.setToolTipText("");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel38.add(jLabel13, java.awt.BorderLayout.CENTER);

        jPanel37.add(jPanel38, java.awt.BorderLayout.WEST);

        jPanel39.setBackground(new java.awt.Color(58, 120, 220));
        jPanel39.setLayout(new java.awt.BorderLayout());

        jPanel40.setBackground(new java.awt.Color(58, 120, 220));
        jPanel40.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel39.add(jPanel40, java.awt.BorderLayout.EAST);

        jLabel14.setFont(new java.awt.Font("Orbitron", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("   000.00");
        jLabel14.setToolTipText("");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel39.add(jLabel14, java.awt.BorderLayout.CENTER);

        jPanel37.add(jPanel39, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel37);

        jPanel41.setLayout(new java.awt.BorderLayout());

        jPanel42.setBackground(new java.awt.Color(58, 120, 220));
        jPanel42.setPreferredSize(new java.awt.Dimension(200, 58));
        jPanel42.setLayout(new java.awt.BorderLayout());

        jLabel15.setFont(new java.awt.Font("Orbitron", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("   Descuento");
        jLabel15.setToolTipText("");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel42.add(jLabel15, java.awt.BorderLayout.CENTER);

        jPanel41.add(jPanel42, java.awt.BorderLayout.WEST);

        jPanel43.setBackground(new java.awt.Color(58, 120, 220));
        jPanel43.setLayout(new java.awt.BorderLayout());

        jPanel44.setBackground(new java.awt.Color(58, 120, 220));
        jPanel44.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel43.add(jPanel44, java.awt.BorderLayout.EAST);

        jLabel16.setFont(new java.awt.Font("Orbitron", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("   000.00");
        jLabel16.setToolTipText("");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel43.add(jLabel16, java.awt.BorderLayout.CENTER);

        jPanel41.add(jPanel43, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel41);

        jPanel45.setLayout(new java.awt.BorderLayout());

        jPanel46.setBackground(new java.awt.Color(58, 120, 220));
        jPanel46.setPreferredSize(new java.awt.Dimension(200, 58));
        jPanel46.setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("Orbitron", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("   Sueldo neto");
        jLabel17.setToolTipText("");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel46.add(jLabel17, java.awt.BorderLayout.CENTER);

        jPanel45.add(jPanel46, java.awt.BorderLayout.WEST);

        jPanel47.setBackground(new java.awt.Color(58, 120, 220));
        jPanel47.setLayout(new java.awt.BorderLayout());

        jPanel48.setBackground(new java.awt.Color(58, 120, 220));
        jPanel48.setPreferredSize(new java.awt.Dimension(20, 58));

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel47.add(jPanel48, java.awt.BorderLayout.EAST);

        jLabel18.setFont(new java.awt.Font("Orbitron", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("   000.00");
        jLabel18.setToolTipText("");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel47.add(jLabel18, java.awt.BorderLayout.CENTER);

        jPanel45.add(jPanel47, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel45);

        jPanel49.setBackground(new java.awt.Color(58, 120, 220));
        jPanel49.setLayout(new java.awt.BorderLayout());

        jPanel50.setBackground(new java.awt.Color(58, 120, 220));
        jPanel50.setPreferredSize(new java.awt.Dimension(40, 58));
        jPanel50.setLayout(new java.awt.BorderLayout());
        jPanel49.add(jPanel50, java.awt.BorderLayout.WEST);

        jButton8.setBackground(new java.awt.Color(102, 102, 255));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Calcular");
        jPanel49.add(jButton8, java.awt.BorderLayout.CENTER);

        jPanel51.setBackground(new java.awt.Color(58, 120, 220));
        jPanel51.setPreferredSize(new java.awt.Dimension(40, 0));
        jPanel51.setLayout(new java.awt.BorderLayout());
        jPanel49.add(jPanel51, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel49);

        centerUpPanel.add(jPanel1);

        centerPanel.add(centerUpPanel, java.awt.BorderLayout.PAGE_START);

        centerDownPanel.setBackground(new java.awt.Color(28, 34, 59));
        centerDownPanel.setPreferredSize(new java.awt.Dimension(300, 300));
        centerDownPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(102, 102, 255));

        jTable2.setBackground(new java.awt.Color(204, 204, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setFocusable(false);
        jTable2.setRowHeight(25);
        jTable2.setRowMargin(1);
        jScrollPane2.setViewportView(jTable2);

        centerDownPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        centerPanel.add(centerDownPanel, java.awt.BorderLayout.CENTER);

        rooPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(rooPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel centerDownPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel centerUpPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel100;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel81;
    private javax.swing.JPanel jPanel82;
    private javax.swing.JPanel jPanel83;
    private javax.swing.JPanel jPanel84;
    private javax.swing.JPanel jPanel85;
    private javax.swing.JPanel jPanel86;
    private javax.swing.JPanel jPanel87;
    private javax.swing.JPanel jPanel88;
    private javax.swing.JPanel jPanel89;
    private javax.swing.JPanel jPanel90;
    private javax.swing.JPanel jPanel91;
    private javax.swing.JPanel jPanel92;
    private javax.swing.JPanel jPanel93;
    private javax.swing.JPanel jPanel94;
    private javax.swing.JPanel jPanel95;
    private javax.swing.JPanel jPanel96;
    private javax.swing.JPanel jPanel97;
    private javax.swing.JPanel jPanel98;
    private javax.swing.JPanel jPanel99;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel rooPanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
